# Generated by Django 5.1.3 on 2024-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='noImage.png', null=True, upload_to='', verbose_name='アイコン'),
        ),
    ]
