# Generated by Django 5.1.3 on 2024-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50, verbose_name='作品名')),
                ('content', models.TextField(verbose_name='本文')),
                ('tag1', models.CharField(max_length=50, verbose_name='タグ1')),
                ('tag2', models.CharField(blank=True, max_length=50, verbose_name='タグ2')),
                ('tag3', models.CharField(blank=True, max_length=50, verbose_name='タグ3')),
                ('give_character', models.CharField(max_length=50, verbose_name='譲渡キャラ名')),
                ('want_character', models.CharField(max_length=50, verbose_name='希望キャラ名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('type_transaction', models.PositiveIntegerField(choices=[(1, '交換'), (2, '譲渡')], verbose_name='交換or譲渡')),
                ('type_transfer', models.PositiveIntegerField(choices=[(1, '郵送'), (2, '手渡し')], verbose_name='郵送or手渡し')),
                ('image1', models.ImageField(upload_to='', verbose_name='画像1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='画像2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='画像3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
