# Generated by Django 5.1.3 on 2024-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODstime', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('unmatched', '取引未成立'), ('matched', '取引成立')], default='unmatched', max_length=20, null=True, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_name',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
