# Generated by Django 5.1.3 on 2024-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODstime', '0006_review_post_alter_message_post_alter_post_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('unmatched', '取引未成立'), ('matched', '取引成立'), ('completed', '取引完了')], default='unmatched', max_length=20, null=True, verbose_name='ステータス'),
        ),
    ]
