# Generated by Django 4.2.16 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODstime', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_flg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_name',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
