# Generated by Django 4.2.16 on 2024-11-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOODstime', '0008_post_delete_flg_alter_post_work_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='delete_flg',
        ),
    ]
