# Generated by Django 4.2.16 on 2024-12-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOODstime', '0009_remove_report_delete_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='お問い合わせ内容')),
            ],
        ),
    ]
